# Generated by Django 4.1.2 on 2023-10-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('year_joined', models.IntegerField(max_length=4)),
            ],
        ),
    ]
