# Generated by Django 4.1.2 on 2023-10-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readcsvfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='age',
            field=models.IntegerField(),
        ),
    ]
