# Generated by Django 4.1.2 on 2023-10-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvhandler', '0002_rename_name_item_staff_name_remove_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='year_joined',
            field=models.IntegerField(max_length=4),
        ),
    ]
